#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/

$app = require __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

define('APP_ENV', env('APP_ENV'));

mb_internal_encoding("UTF-8");

date_default_timezone_set("Europe/Moscow");

$app->register('LaravelSingleInstanceCommand\ServiceProvider');

$logger = app('log');
$logger->popHandler(); // выкидываем запись в файл
$logger->pushHandler(new Monolog\Handler\ErrorLogHandler()); // включаем запись в консоль

$kernel = $app->make(
    'Illuminate\Contracts\Console\Kernel'
);

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
