nginx:
  image: "nginx:stable"
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/etc/ssl/:/etc/ssl/"
    - "/root/docker/vmeste/nginx/:/etc/nginx/"
    - "/home/vmeste/:/home/vmeste/"
    - "/home/test-vmeste/:/home/test-vmeste/"
  container_name: nginx

