<?php

$suffix = env('APP_ENV') === 'test' ? '_test' : '';

return [
    'fetch' => PDO::FETCH_CLASS,
    'default' => 'vmeste',
    'connections' => [
        'vmeste' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_VMESTE_HOST', ''),
            'port'     => env('DB_VMESTE_PORT', '5432'),
            'database' => env('DB_VMESTE_DATABASE', ''),
            'username' => env('DB_VMESTE_USERNAME', ''),
            'password' => env('DB_VMESTE_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
        'gis' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_GIS_HOST', ''),
            'port'     => env('DB_GIS_PORT', '5432'),
            'database' => env('DB_GIS_DATABASE', ''),
            'username' => env('DB_GIS_USERNAME', ''),
            'password' => env('DB_GIS_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
        'matches0' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_MATCHES_HOST', ''),
            'port'     => env('DB_MATCHES_PORT', '5432'),
            'database' => 'matches0' . $suffix,
            'username' => env('DB_MATCHES_USERNAME', ''),
            'password' => env('DB_MATCHES_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
        'matches1' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_MATCHES_HOST', ''),
            'port'     => env('DB_MATCHES_PORT', '5432'),
            'database' => 'matches1' . $suffix,
            'username' => env('DB_MATCHES_USERNAME', ''),
            'password' => env('DB_MATCHES_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
        'matches2' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_MATCHES_HOST', ''),
            'port'     => env('DB_MATCHES_PORT', '5432'),
            'database' => 'matches2' . $suffix,
            'username' => env('DB_MATCHES_USERNAME', ''),
            'password' => env('DB_MATCHES_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
        'matches3' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_MATCHES_HOST', ''),
            'port'     => env('DB_MATCHES_PORT', '5432'),
            'database' => 'matches3' . $suffix,
            'username' => env('DB_MATCHES_USERNAME', ''),
            'password' => env('DB_MATCHES_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
        'matches4' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_MATCHES_HOST', ''),
            'port'     => env('DB_MATCHES_PORT', '5432'),
            'database' => 'matches4' . $suffix,
            'username' => env('DB_MATCHES_USERNAME', ''),
            'password' => env('DB_MATCHES_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
        'matches5' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_MATCHES_HOST', ''),
            'port'     => env('DB_MATCHES_PORT', '5432'),
            'database' => 'matches5' . $suffix,
            'username' => env('DB_MATCHES_USERNAME', ''),
            'password' => env('DB_MATCHES_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
        'matches6' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_MATCHES_HOST', ''),
            'port'     => env('DB_MATCHES_PORT', '5432'),
            'database' => 'matches6' . $suffix,
            'username' => env('DB_MATCHES_USERNAME', ''),
            'password' => env('DB_MATCHES_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
        'matches7' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_MATCHES_HOST', ''),
            'port'     => env('DB_MATCHES_PORT', '5432'),
            'database' => 'matches7' . $suffix,
            'username' => env('DB_MATCHES_USERNAME', ''),
            'password' => env('DB_MATCHES_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
        'matches8' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_MATCHES_HOST', ''),
            'port'     => env('DB_MATCHES_PORT', '5432'),
            'database' => 'matches8' . $suffix,
            'username' => env('DB_MATCHES_USERNAME', ''),
            'password' => env('DB_MATCHES_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
        'matches9' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_MATCHES_HOST', ''),
            'port'     => env('DB_MATCHES_PORT', '5432'),
            'database' => 'matches9' . $suffix,
            'username' => env('DB_MATCHES_USERNAME', ''),
            'password' => env('DB_MATCHES_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
        'logs' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_LOGS_HOST', ''),
            'port'     => env('DB_LOGS_PORT', '5432'),
            'database' => env('DB_LOGS_DATABASE', ''),
            'username' => env('DB_LOGS_USERNAME', ''),
            'password' => env('DB_LOGS_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'options'   => array(
                PDO::ATTR_EMULATE_PREPARES => true,
            ),
        ],
    ],
    'migrations' => 'migrations',

    'redis' => [
        'cluster' => false,
        'default' => [
            'host'     => '127.0.0.1',
            'port'     => 6379,
            'database' => 0,
        ],
    ],

    'images_storage_path' => env('ROOT_PATH', '') . env('PHOTOS_PATH', ''),
];
